version: '3'

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - |
        protoc -I proto  \
          -I $(go env GOPATH)/pkg/mod/github.com/envoyproxy/protoc-gen-validate@v1.2.1 \
          proto/sso/sso.proto \
          --go_out=./gen/go --go_opt=paths=source_relative \
          --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative \
          --validate_out=lang=go,paths=source_relative:./gen/go 
          
